workflows:
  my-workflow:
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: master
          include: false
      cancel_previous_builds: true
    environment:
      #vars:
         # XCODE_WORKSPACE: "PhotoSearch.xcodeproj"
         # XCODE_SCHEME: "PhotoSearch"
      xcode: 12.5
    scripts:
      - name: say hello
        script: echo "Hello Codemagician!"
      - name: Run iOS tests
        script: |
          set -e # exit on first failed command

          xcode-project run-tests \
              --project ${XCODE_WORKSPACE?} \
              --scheme ${XCODE_SCHEME?} \
              --device "iPhone 12"
        test_report: build/ios/test/*.xml


